
import { User, RegistrationRequest } from '../types';

/**
 * DATABASE SERVICE (Supabase/PostgreSQL Bridge)
 * Menggunakan REST API standar untuk kompatibilitas maksimal tanpa npm install tambahan.
 */

export const databaseService = {
  /**
   * Mengirim data user tunggal ke Database (Tabel Users)
   */
  upsertUser: async (config: { url: string; key: string }, user: User) => {
    if (!config.url || !config.key) return;

    const baseUrl = config.url.replace(/\/$/, "");
    const endpoint = `${baseUrl}/rest/v1/users`;

    const payload = {
      user_id: user.id,
      full_name: user.name,
      email: user.email,
      role: user.role,
      whatsapp: user.whatsapp || null,
      status: user.status || 'active',
      subscription_expiry: user.subscriptionExpiry || null,
      performance_score: user.performanceScore || 0,
      last_updated: new Date().toISOString()
    };

    try {
      const response = await fetch(endpoint, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'apikey': config.key,
          'Authorization': `Bearer ${config.key}`,
          'Prefer': 'resolution=merge-duplicates'
        },
        body: JSON.stringify(payload)
      });

      if (!response.ok) throw new Error(`DB Error: ${response.statusText}`);
      return true;
    } catch (error) {
      console.error("Database Sync Error:", error);
      throw error;
    }
  },

  /**
   * Mendaftarkan user baru ke tabel 'registrations' (Public Registration)
   */
  createRegistration: async (config: { url: string; key: string }, data: any) => {
    if (!config.url || !config.key) throw new Error("Database belum terkonfigurasi di sisi Admin.");

    const baseUrl = config.url.replace(/\/$/, "");
    const endpoint = `${baseUrl}/rest/v1/registrations`;

    const payload = {
      name: data.name,
      email: data.email,
      password: data.password, // Added Password Field
      whatsapp: data.whatsapp,
      reason: data.reason,
      status: 'pending', // Default status for monitoring app
      created_at: new Date().toISOString()
    };

    try {
      const response = await fetch(endpoint, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'apikey': config.key,
          'Authorization': `Bearer ${config.key}`,
          'Prefer': 'return=minimal'
        },
        body: JSON.stringify(payload)
      });

      if (!response.ok) throw new Error(`Registration Failed: ${response.statusText}`);
      return true;
    } catch (error) {
      console.error("Registration Error:", error);
      throw error;
    }
  },

  /**
   * Mengambil data registrasi yang sudah di-APPROVE oleh aplikasi monitoring
   */
  fetchApprovedRegistrations: async (config: { url: string; key: string }) => {
    if (!config.url || !config.key) return [];

    const baseUrl = config.url.replace(/\/$/, "");
    // Filter status=eq.approved
    const endpoint = `${baseUrl}/rest/v1/registrations?status=eq.approved&select=*`;

    try {
      const response = await fetch(endpoint, {
        method: 'GET',
        headers: {
          'apikey': config.key,
          'Authorization': `Bearer ${config.key}`,
        }
      });

      if (!response.ok) return [];
      const data = await response.json();
      return data;
    } catch (error) {
      console.error("Fetch Approved Error:", error);
      return [];
    }
  },

  /**
   * Mendapatkan SQL Schema untuk setup awal (Update V3 - Added Password)
   */
  getSchemaSQL: () => {
    return `
-- TABLE 1: USERS (Untuk User Aktif yang sudah bisa Login)
CREATE TABLE IF NOT EXISTS users (
    user_id VARCHAR(255) PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    role VARCHAR(50) DEFAULT 'viewer',
    whatsapp VARCHAR(50),
    status VARCHAR(50) DEFAULT 'active',
    subscription_expiry DATE,
    performance_score INTEGER DEFAULT 0,
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- TABLE 2: REGISTRATIONS (Update: Added password column)
CREATE TABLE IF NOT EXISTS registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255),
    whatsapp VARCHAR(50),
    reason TEXT,
    status VARCHAR(50) DEFAULT 'pending', -- pending, approved, rejected
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_regs_status ON registrations(status);

-- IMPORTANT: Pastikan RLS (Row Level Security) di Supabase membolehkan INSERT publik 
-- atau nonaktifkan RLS untuk tabel 'registrations' agar form registrasi bisa masuk.
    `.trim();
  }
};
